### ISSUE TITLE
When running `wml start` nothing happen

### ISSUE THREAD

**Issue by idangozlan** [wix/wml#17]
I use to work with wml start on my old mac, then switch to a new one, now `wml start` doesnt do nothing. Anyway to print debug log or something that can lead to the problem?

**Comment by Scit** [comment]
Having the same.

Ubuntu 16.04, watchman v. 4.9.1

**Comment by madflanderz** [comment]
I had the same problem. In my case i had a bad npm environment and i installed wml with sudo. If you did this you have to use sudo also when you add links:

`sudo npm install -g wml`
`sudo wml add ./src ./dest`
`wml list`
`wml start`

Better solution is use node version manager. Then you don't need to install packages with sudo.

**Comment by henninghall** [comment]
Same problem on ubuntu, works perfectly on mac

**Comment by henninghall** [comment]
Solved it by installing the newest version of watchman

**Comment by henninghall** [comment]
Solved it by installing the latest version of watchman

**Comment by bantingGamer** [comment]
> of

what version of watchman did you install? becasue i still just have a cursor flashing...

**Comment by LordDraagonLive** [comment]
I'm facing thee same issue in windows 10

**Comment by pmontu** [comment]
I am facing the same issue. I did not try installing watchman again. I am using bionic beaver

**Comment by SackeyDavid** [comment]
Pleasse how do we fix it on windows 10?

**Comment by SackeyDavid** [comment]
fixed using npm-link https://medium.com/dailyjs/how-to-use-npm-link-7375b6219557 on Windows 10. But this is problematic because npm-link which uses symbolic linking doesn't work with the metro bundler facebook/metro#1.

**Comment by pmontu** [comment]
I moved from node 9 to 10(using nvm) and installed wml again. now wml opens up super fast.

**Comment by SackeyDavid** [comment]
> I moved from node 9 to 10(using nvm) and installed wml again. now wml opens up super fast.

Hmm, thanks @pmontu for the reply. I'm using node version 12.4.0 on Windows 10 and it's still not working with the metro bundler. Are you using Windows 10 please?

**Comment by MirceaTheOldMan** [comment]
I've tried with node 8.16.0, 10.16.0 and 12.4.0 but it doesn't do anything when I write `wml start`.
All the other commands worked fine. `wml add` created that .watchmanconfig file.
I'm using Windows 10 Home, watchman 4.9.4

**Comment by SackeyDavid** [comment]
> 
> 
> I've tried with node 8.16.0, 10.16.0 and 12.4.0 but it doesn't do anything when I write `wml start`.
> All the other commands worked fine. `wml add` created that .watchmanconfig file.
> I'm using Windows 10 Home, watchman 4.9.4

Hi @MirceaTheOldMan, after countless futile attempts to fix this problem on windows 10, I've finally decided to work on Mac OS. And it works fine there.

Now, I want to work on a library to fix that for windows 10. I'll like some interested persons to collaborate with me on this. Since facebook metro hasn't said they plan working on symlinks and wix/wml hasn't said anything too, I think something needs to done for windows 10 users.

**Comment by stackoverjoe** [comment]
> I've tried with node 8.16.0, 10.16.0 and 12.4.0 but it doesn't do anything when I write `wml start`.
> All the other commands worked fine. `wml add` created that .watchmanconfig file.
> I'm using Windows 10 Home, watchman 4.9.4

I am having the exact same issue. Can run all commands fine except start. The problem seems to lie in watchman for windows 10.

**Comment by MirceaTheOldMan** [comment]
I've tested `wml start` on OSX and Linux and they work fine. What if this is somehow related to the way the path (as parameters for the `add` command) is written in **OSX** / **Linux** versus **Windows**?

**Comment by MirceaTheOldMan** [comment]
I found a partial solution for "Windows":

1. Install **WSL** (Windows Subsystem for Linux);
2. Install **Ubuntu** and **update** it's packages;
3. Install **watchman**;
4. Install **nodejs** (no specific version mandatory) inside Ubuntu
5. and lastly. Install **wml** inside Ubuntu.

**Note:**
You'll only be able to use wml inside Ubuntu, meaning that the project (the watched folder and the destination) must be inside Ubuntu's root folder or it's child folders.
Make sure to read WSL's documentation because with latest version of windows(1903) you can view that folder and even use VS Code to create and edit files in that folder, from within Windows, not from Linux.
**Conclusion:**
You just use the whole WSL with Linux console to watch the folder that needs duplication. The other part of code implementation can be easily done from VS Code.

**Comment by LordDraagonLive** [comment]
That's lot of steps to install a package but really grateful for your effort. I hope will find a more simpler way to achieve this.

**Comment by wushq5** [comment]
add the wml/src dir to watchman list will do, like this
`watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`

**Comment by SevenZark** [comment]
I having this issue in Windows 10. wml start just results in a blinking cursor. No changes are detected. The software does nothing. Since this issue has been open for about two years, I guess I'm not hopeful of anyone caring enough to fix..? I sure wish I knew how myself.

**Comment by krunaldholakia01** [comment]
> add the wml/src dir to watchman list will do, like this
> `watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`

Thanks @wushq5 ! 
->First I downloaded latest version of watchman and added it to path environment variable.
-> Installed wml using npm globally
->Then added link to my node_module ( "wml add ..\common .\node_modules\\@wow\common ")

I started using wml start but there was blank screen with cursor blinking.
Last I tried adding wml src folder as per your direction like this
-> watchman watch C:\Users\\%user%\AppData\Roaming\npm\node_modules\wml\src 
That solved issue for me on Windows 10.
☺☺☺

**Comment by SackeyDavid** [comment]
Wow, great

**Comment by hodev-dev** [comment]
same problem windows 10 latest version of watchman installed with chocco

**Comment by huhuang03** [comment]
> > add the wml/src dir to watchman list will do, like this
> > `watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`
> 
> Thanks @wushq5 !
> ->First I downloaded latest version of watchman and added it to path environment variable.
> -> Installed wml using npm globally
> ->Then added link to my node_module ( "wml add ..\common .\node_modules\@wow\common ")
> 
> I started using wml start but there was blank screen with cursor blinking.
> Last I tried adding wml src folder as per your direction like this
> -> watchman watch C:\Users\%user%\AppData\Roaming\npm\node_modules\wml\src
> That solved issue for me on Windows 10.
> ☺☺☺

Yes, it can work, And If not do that, the error log is this on my pc, which I use the wml in F:\wml:
```
PS F:\> wml start
client subscribe end called Error: class RootResolveError: RootResolveError: unable to resolve root F:\wml\src: RootResolveError: directory F:/wml/src is not watched
    at BunserBuf.<anonymous> (F:\wml\node_modules\fb-watchman\index.js:95:23)
    at BunserBuf.emit (events.js:310:20)
    at BunserBuf.process (F:\wml\node_modules\bser\index.js:289:10)
    at F:\wml\node_modules\bser\index.js:244:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  watchmanResponse: {
    version: '20201213.172817.0',
    error: 'class RootResolveError: RootResolveError: unable to resolve root F:\\wml\\src: RootResolveError: directory F:/wml/src is not watched'
  }
}
```

**Comment by quinnwai** [comment]
If there's no source file in 

> `watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`

find where your `wml/src` is installed. For me it was in `~/.config/yarn/global/` since I used `yarn global install wml` to install the package.

**Comment by etash47** [comment]
> If there's no source file in
> 
> > `watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`
> 
> find where your `wml/src` is installed. For me it was in `~/.config/yarn/global/` since I used `yarn global install wml` to install the package.

I had trouble finding where my installation was. I had installed wml globally as well, so I used `npm config get prefix` to find the npm in use, and then appended `lib/node_modules/wml/src` to that path, and then did what QuinnWai said
