### ISSUE TITLE
Watchman:  Watchman was not found in PATH.

### ISSUE THREAD

**Issue by m4tzess** [wix/wml#34]
I keep getting this error when trying to start WML. Does someone have a solution?

`root@server:~# wml start
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
`

Thanks in advance,
-Mathis

**Comment by edzillion** [comment]
The solution is in your error message, you must install watchman:

> Watchman: Watchman was not found in PATH. See https://facebook.github.io/watchman/docs/install.html for installation instructions

**Comment by m4tzess** [comment]
Ah okay! Thanks!

**Comment by theZulqarnain** [comment]
I have the same problem in Linux, I checked above [link](https://facebook.github.io/watchman/docs/install.html) but seem everything good with **inotify**.is there any other solution.
