### ISSUE TITLE
wlm start doesn't load watchman

### ISSUE THREAD

**Issue by bantingGamer** [wix/wml#38]
### The issue
**wml start** does nothing. It is as if it doesn't load watchman. There is just a blank cursor flashing. No changes are copied.

### To replicate
**Install latest watchman** "version": "4.9.4" from [https://facebook.github.io/watchman/docs/install.html](https://facebook.github.io/watchman/docs/install.html)
**install wml** npm install -g wml
**Configure wml** wml add ~/my-package ~/main-project/node_modules/my-package
**run wml** wml start
**and nothing**

### Thank you for your time

**Comment by ABQJuan** [comment]
Same problem here.
wml add, rm, list etc all work fine. 
wml start just results in a blinking cursor on the next line. No output. No changes.

Windows 10

**Comment by randadam** [comment]
Same here

Windows 10

**Comment by gabemule** [comment]
Same here.

MacOS

**Comment by wushq5** [comment]
add your wml/src dir to watchman list will do, like this
`watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`

**Comment by SevenZark** [comment]
I am also having this issue on a brand new install of Windows 10. "wml start" just resolves to a blinking cursor. It doesn't actually notice changes or do anything at all except leave a blinking cursor sitting there.

**Comment by SevenZark** [comment]
> add your wml/src dir to watchman list will do, like this
> `watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`

This did not solve anything for me.

**Comment by youngjuning** [comment]
how to use it on windows？

**Comment by youngjuning** [comment]
same issues on windows10

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/71430270-c6b08b80-2705-11ea-9c08-88306a62d84a.png)

**Comment by youngjuning** [comment]
@wushq5 thanks for your help

**Comment by hosseinalipour** [comment]
it's sucks. which path do I need to watch by the watchman. it doesn't work.

**Comment by gcandal** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/13204332/71430270-c6b08b80-2705-11ea-9c08-88306a62d84a.png)

Under `scoop` + `nvm` running `watchman watch C:\Users\%user\scoop\apps\nvm\current\nodejs\nodejs\node_modules\wml\src` seems to work.

**Comment by daominhsangvn** [comment]
For people who late that have this issue:
Steps by step how to run WML
- Install `wml`: `$ npm install -g wml`
- Install Watchman:
    - Windows: https://github.com/facebook/watchman/releases (Add to PATH and restart terminal)
    - MacOS: `$ brew update && brew install watchman`
- Delete existing watches: `$ watchman watch-del-all`
- Activate `watchman` for `wml`: `$ watchman watch "C:\Program Files\nodejs\node_modules\wml\src"`
    -  (Windows) Find nodejs package location: `$ npm list -g --depth 0 | head -1` > You will see something like this `C:\Program Files\nodejs`
    - (MacOS) Find nodejs location: `$ which node`
- Add link: `$ wml add <package to sync location> <dest package location>`
- Watch & Sync: `$ wml start`

**Comment by zatlodan** [comment]
> For people who late that have this issue:
> Steps by step how to run WML
> 
> * Install `wml`: `$ npm install -g wml`
> * Install Watchman:
>   
>   * Windows: https://github.com/facebook/watchman/releases (Add to PATH and restart terminal)
>   * MacOS: `$ brew update && brew install watchman`
> * Delete existing watches: `$ watchman watch-del-all`
> * Activate `watchman` for `wml`: `$ watchman watch "C:\Program Files\nodejs\node_modules\wml\src"`
>   
>   * (Windows) Find nodejs package location: `$ npm list -g --depth 0 | head -1` > You will see something like this `C:\Program Files\nodejs`
>   * (MacOS) Find nodejs location: `$ which node`
> * Add link: `$ wml add <package to sync location> <dest package location>`
> * Watch & Sync: `$ wml start`

Awesome, thanks, this works like a charm! Just a note that on linux and nvm the `wml/src` folder is located here: `/home/<your_home_folder_name>/.nvm/versions/node/v<your_version_of_node>/lib/node_modules/wml/src`

**Comment by kopax-polyconseil** [comment]
I have tried not to install wml globally, and result was bad.

Chao ban va xin cam on, this should be in the README, the most important part is the step `active watchman`, as soon as you map this correctly, you will see output when running `wml start`.

However, it's not because I see wml logging that I see file updating, it still seems that wml is not doing anything but logging.

Any clue how I can solve the linking problem betweenn a module and a native application?

**Comment by Foskas** [comment]
> For people who late that have this issue:
> Steps by step how to run WML
> 
> * Install `wml`: `$ npm install -g wml`
> * Install Watchman:
>   
>   * Windows: https://github.com/facebook/watchman/releases (Add to PATH and restart terminal)
>   * MacOS: `$ brew update && brew install watchman`
> * Delete existing watches: `$ watchman watch-del-all`
> * Activate `watchman` for `wml`: `$ watchman watch "C:\Program Files\nodejs\node_modules\wml\src"`
>   
>   * (Windows) Find nodejs package location: `$ npm list -g --depth 0 | head -1` > You will see something like this `C:\Program Files\nodejs`
>   * (MacOS) Find nodejs location: `$ which node`
> * Add link: `$ wml add <package to sync location> <dest package location>`
> * Watch & Sync: `$ wml start`

Hi @daominhsangvn 

I did which node on my mac and I got /Users/pedrosaraiva/.nvm/versions/node/v16.1.0/bin/node but if I try to execute the comment "watchman watch /Users/pedrosaraiva/.nvm/versions/node/v16.1.0/bin/node/node_modules/wml/src" it is saying it is not a directory.

I did which wml and it returns "/opt/homebrew/bin/wml" but it gives me the same output if I try to run the command "watchman watch /opt/homebrew/bin/wml/src"

Do you have any other ideas ?

**Comment by andresesfm** [comment]
In my case, I followed @daominhsangvn 's instructions (MacOS) but since I'm using `n` I couldn't get the location of `node_modules/wml/src` by using `which node`. I found a more accurate way by using:
`npm root -g` Reference: https://stackoverflow.com/a/54996486

**Comment by vinikatyal** [comment]
> In my case, I followed @daominhsangvn 's instructions (MacOS) but since I'm using `n` I couldn't get the location of `node_modules/wml/src` by using `which node`. I found a more accurate way by using:
> `npm root -g` Reference: https://stackoverflow.com/a/54996486

Thanks for this!

**Comment by L-Simona** [comment]
@daominhsangvn Thank you! It works!

**Comment by tylers-username** [comment]
For those of you having trouble finding the path on macOS or Linux, this should help:

`watchman watch $(dirname /$(readlink $(which wml)))/../wml/src`

**Comment by reactoholic** [comment]
> add your wml/src dir to watchman list will do, like this `watchman watch /Users/rcrabwu/.nvm/versions/node/v8.9.0/lib/node_modules/wml/src`

When I did this wml start throws an error :

```
[error] watchman::RootResolveError: failed to resolve root: unable to resolve root /Users/pkolev/projects/bytesmiths/homeco2ntrol-lib/src: failed to resolve root: directory /Users/pkolev/projects/bytesmiths/homeco2ntrol-lib/src is not watched
/Users/pkolev/.nvm/versions/node/v20.12.2/lib/node_modules/wml/node_modules/q/q.js:155
                throw e;
                ^

Error: watchman::RootResolveError: failed to resolve root: unable to resolve root /Users/pkolev/projects/bytesmiths/homeco2ntrol-lib/src: failed to resolve root: directory /Users/pkolev/projects/bytesmiths/homeco2ntrol-lib/src is not watched
    at BunserBuf.<anonymous> (/Users/pkolev/.nvm/versions/node/v20.12.2/lib/node_modules/wml/node_modules/fb-watchman/index.js:95:23)
    at BunserBuf.emit (node:events:518:28)
    at BunserBuf.process (/Users/pkolev/.nvm/versions/node/v20.12.2/lib/node_modules/wml/node_modules/bser/index.js:289:10)
    at /Users/pkolev/.nvm/versions/node/v20.12.2/lib/node_modules/wml/node_modules/bser/index.js:244:12
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  watchmanResponse: {
    error: 'watchman::RootResolveError: failed to resolve root: unable to resolve root /Users/pkolev/projects/bytesmiths/homeco2ntrol-lib/src: failed to resolve root: directory /Users/pkolev/projects/bytesmiths/homeco2ntrol-lib/src is not watched',
    version: '2024.07.15.00'
  }
}

Node.js v20.12.2
```
