### ISSUE TITLE
cannot start watching

### ISSUE THREAD

**Issue by idancali** [wix/wml#9]
I just installed the latest version of wml and I added a link. But when running the ```start``` command I get an error

```
Error: unable to resolve root 
```

Looks like the error occurs here:

```
fb-watchman/index.js:95:23
```

**Comment by conor909** [comment]
Same here

```
Error: unable to resolve root /Users/my-user-name/dev/my-project/my-app: directory /Users/my-user-name/dev/my-project/my-app is not watched
    at BunserBuf.<anonymous> (/usr/local/lib/node_modules/wml/node_modules/fb-watchman/index.js:95:23)
    at emitOne (events.js:96:13)
    at BunserBuf.emit (events.js:189:7)
    at BunserBuf.process (/usr/local/lib/node_modules/wml/node_modules/bser/index.js:289:10)
    at /usr/local/lib/node_modules/wml/node_modules/bser/index.js:244:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by zheng-liu-seattle** [comment]
+1

**Comment by p4bloch** [comment]
Same problem happening here, node 7.5 and not sure what wml version (can't see it in help output)

**Comment by ArtisanalPickle** [comment]
Same, seems to only happen for me when linking from a source that's any deeper than one level, e.g. `wml add source_dir dest_dir/node_modules/source_dir` works just fine, but it fails when I do `wml add source_dir/src dest_dir/node_modules/source_dir`

**Comment by littlehome-eugene** [comment]
Weird, on one machine it works fine, on one machine it doesn't.  

both use wml 0.0.82
node 4.7.0
npm 2.15.11

**Comment by robertsami** [comment]
+1

**Comment by jordmccord** [comment]
https://github.com/wix/wml/issues/1#issuecomment-234774566
